--------------------------------------------------------
--  File created - Wednesday-August-16-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHARACTERS
--------------------------------------------------------

  CREATE TABLE "DB970"."CHARACTERS" 
   (	"ID" NUMBER(*,0), 
	"CHAMPION" VARCHAR2(100 BYTE), 
	"CLASSES" VARCHAR2(50 BYTE), 
	"RELEASE_DATE" DATE, 
	"BLUE_ESSENCE" NUMBER(*,0), 
	"RP" NUMBER(*,0), 
	"DAMAGE" VARCHAR2(50 BYTE), 
	"RESOURCE_BAR" VARCHAR2(50 BYTE), 
	"POSITION_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00148824
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB970"."SYS_C00148824" ON "DB970"."CHARACTERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  Constraints for Table CHARACTERS
--------------------------------------------------------

  ALTER TABLE "DB970"."CHARACTERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
